---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - role: setup
    - role: nginx
    - role: config
    - role: jupyter-notebook
    - role: facts
    - role: cleanup
